apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mobileye
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: hello-mobileye
          image: 230417554355.dkr.ecr.us-east-1.amazonaws.com/web-image:latest
          ports:
            - containerPort: 80
              protocol: TCP